Laboratorio1/Laboratorio1/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstudianteEntities : DbContext
    {
        public EstudianteEntities()
            : base("name=EstudianteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblNotasEstudiante> TblNotasEstudiante { get; set; }
    }
}

Laboratorio1/Laboratorio1/Models/Model1.Designer.cs
// La generación de código T4 está habilitada para el modelo 'D:\Proyectos Web\Laboratorio1\Laboratorio1\Models\Model1.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

Laboratorio1/Laboratorio1/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

Laboratorio1/Laboratorio1/Models/TblNotasEstudiante.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotasEstudiante
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> lab1 { get; set; }
        public Nullable<decimal> lab2 { get; set; }
        public Nullable<decimal> lab3 { get; set; }
        public Nullable<decimal> par1 { get; set; }
        public Nullable<decimal> par2 { get; set; }
        public Nullable<decimal> par3 { get; set; }
    }
}

Laboratorio1/Laboratorio1/Controllers/NotasController.cs
using Laboratorio1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio1.Controllers
{
    public class NotasController : Controller
    {
        // GET: Notas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Resultado() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult Resultado(string Nombre,float lab1,float lab2, float lab3, float par1, float par2, float par3)
        {
            TblNotasEstudiante notas = new TblNotasEstudiante();
            double nota1 = (lab1 * 0.40) + (par1 * 0.60);
            double nota2 = (lab2 * 0.40) + (par2 * 0.60);
            double nota3 = (lab3 * 0.40) + (par3 * 0.60);

            ViewBag.Resultado = Convert.ToDecimal((nota1 + nota2 + nota3)/3);
            using (EstudianteEntities db = new EstudianteEntities())
            {
                notas.Nombre = Nombre;
                notas.lab1 = Convert.ToDecimal(lab1);
                notas.lab2 = Convert.ToDecimal(lab2);
                notas.lab3 = Convert.ToDecimal(lab3);
                notas.par1 = Convert.ToDecimal(par1);
                notas.par2 = Convert.ToDecimal(par2);
                notas.par3 = Convert.ToDecimal(par3);

                db.TblNotasEstudiante.Add(notas);
                db.SaveChanges();
                    
            }
                return View();
        }

        public ActionResult Historial() 
        {
            using (EstudianteEntities db = new EstudianteEntities()) 
            {
                var listado = db.TblNotasEstudiante.ToList();

                return View(listado);
            }

                
        }
    }
}

Laboratorio1/Laboratorio1/Views/Notas/Historial.cshtml
@model List<Laboratorio1.Models.TblNotasEstudiante>
@{
    ViewBag.Title = "Historial";
}

<h2>Historial</h2>

<table class="table table-dark table-striped">
    <thead>
    <th>Nombre </th>
    <th>Laboratorio 1 </th>
    <th>Parcial 1 </th>
    <th>Laboratorio 2 </th>
    <th>Parcial 2 </th>
    <th>Laboratorio 3 </th>
    <th>Parcial 3 </th>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nombre</td>

                <td>@item.lab1</td>

                <td>@item.par1</td>

                <td>@item.lab2</td>

                <td>@item.par2</td>

                <td>@item.lab3</td>

                <td>@item.par3</td>

                 </tr>
        }

    </tbody>
</table>

Laboratorio1/Laboratorio1/Views/Notas/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Resultado", "Notas", FormMethod.Post))
{
    <label for="Nombre">Nombre</label>
    <input type="text" name="Nombre" id="Nombre" class="form-control"/>
    <br />
    <label for="lab1">Laboratorio 1</label>
    <input type="text" name="lab1" id="lab1" class="form-control"/>
    <br />
    <label for="par1">Parcial 1</label>
    <input type="text" name="par1" id="par1" class="form-control"/>
    <br />
    <label for="lab2">Laboratorio 2</label>
    <input type="text" name="lab2" id="lab2" class="form-control"/>
    <br />
    <label for="par2">Parcial 2</label>
    <input type="text" name="par2" id="par2" class="form-control"/>
    <br />
    <label for="lab3">Laboratorio 3</label>
    <input type="text" name="lab3" id="lab3" class="form-control"/>
    <br />
    <label for="par3">Parcial 3</label>
    <input type="text" name="par3" id="par3" class="form-control"/>
    <br />
    <input type="submit" value="Calcular" />
}

Laboratorio1/Laboratorio1/Views/Notas/Resultado.cshtml
@{
    ViewBag.Title = "Resultado";
}

<h1>Resultado</h1>

<label>@ViewBag.Resultado</label>

Laboratorio1/Laboratorio1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Notas")</li>
                    <li>@Html.ActionLink("Alumnos", "Historial", "Notas")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>